# Generated by Django 3.1.1 on 2021-09-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image_handler',
            fields=[
                ('my_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
